omnisport/src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EquipeRepository::class)]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_equipe = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column(length: 255)]
    private ?string $dirigeant = null;

    #[ORM\ManyToOne(inversedBy: 'equipe')]
    private ?Section $section = null;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Licencie::class)]
    private Collection $licencie;

    public function __construct()
    {
        $this->licencie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEquipe(): ?string
    {
        return $this->nom_equipe;
    }

    public function setNomEquipe(string $nom_equipe): self
    {
        $this->nom_equipe = $nom_equipe;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDirigeant(): ?string
    {
        return $this->dirigeant;
    }

    public function setDirigeant(string $dirigeant): self
    {
        $this->dirigeant = $dirigeant;

        return $this;
    }

    public function getSection(): ?Section
    {
        return $this->section;
    }

    public function setSection(?Section $section): self
    {
        $this->section = $section;

        return $this;
    }

    /**
     * @return Collection<int, Licencie>
     */
    public function getLicencie(): Collection
    {
        return $this->licencie;
    }

    public function addLicencie(Licencie $licencie): self
    {
        if (!$this->licencie->contains($licencie)) {
            $this->licencie->add($licencie);
            $licencie->setEquipe($this);
        }

        return $this;
    }

    public function removeLicencie(Licencie $licencie): self
    {
        if ($this->licencie->removeElement($licencie)) {
            // set the owning side to null (unless already changed)
            if ($licencie->getEquipe() === $this) {
                $licencie->setEquipe(null);
            }
        }

        return $this;
    }
}

omnisport/src/Form/EquipeType.php
<?php

namespace App\Form;

use App\Entity\Equipe;
use App\Entity\Section;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class EquipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_equipe')
            ->add('photo', FileType::class, [
                'label' => 'Photo',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '5000k',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Image trop lourde',
                    ])
                ],
            ])
            ->add('dirigeant')
            ->add('section', EntityType::class, [ 'class' => Section::class, 'choice_label' => 'nom_section', ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Equipe::class,
        ]);
    }
}

omnisport/src/Controller/EquipeController.php
<?php

namespace App\Controller;

use App\Entity\Equipe;
use App\Form\EquipeType;
use App\Repository\EquipeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/equipe')]
class EquipeController extends AbstractController
{
    #[Route('/', name: 'app_equipe_index', methods: ['GET'])]
    public function index(EquipeRepository $equipeRepository ): Response
    {
        return $this->render('equipe/index.html.twig', [
            'equipes' => $equipeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_equipe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EquipeRepository $equipeRepository, SluggerInterface $slugger): Response
    {
        $equipe = new Equipe();
        $form = $this->createForm(EquipeType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('photo')->getData();
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
                     
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                $equipe->setPhoto($newFilename);
                $equipeRepository->save($equipe, true);

            return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
        }}

        return $this->renderForm('equipe/new.html.twig', [
            'equipe' => $equipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_equipe_show', methods: ['GET'])]
    public function show(Equipe $equipe): Response
    {
        return $this->render('equipe/show.html.twig', [
            'equipe' => $equipe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_equipe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Equipe $equipe, EquipeRepository $equipeRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(EquipeType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('photo')->getData();
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
                     
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                $equipe->setPhoto($newFilename);
                $equipeRepository->save($equipe, true);

            return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
        }}

        return $this->renderForm('equipe/edit.html.twig', [
            'equipe' => $equipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_equipe_delete', methods: ['POST'])]
    public function delete(Request $request, Equipe $equipe, EquipeRepository $equipeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipe->getId(), $request->request->get('_token'))) {
            $equipeRepository->remove($equipe, true);
        }

        return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
    }
}

omnisport/templates/equipe/_delete_form.html.twig
<form method="post" action="{{ path('app_equipe_delete', {'id': equipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipe.id) }}">
    <button class="btn">Delete</button>
</form>

omnisport/templates/equipe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

omnisport/templates/equipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Equipe{% endblock %}

{% block body %}
    <h1>Edit Equipe</h1>

    {{ include('equipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_equipe_index') }}">back to list</a>

    {{ include('equipe/_delete_form.html.twig') }}
{% endblock %}

omnisport/templates/equipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equipe index{% endblock %}

{% block body %}
    <h1>Equipe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_equipe</th>
                <th>Photo</th>
                <th>Dirigeant</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for equipe in equipes %}
            <tr>
                <td>{{ equipe.id }}</td>
                <td>{{ equipe.nomEquipe }}</td>
                <td><img src="{{ asset('uploads/images/' ~ equipe.photo) }}" width="100"></td>
                <td>{{ equipe.dirigeant }}</td>
                <td>
                    <a href="{{ path('app_equipe_show', {'id': equipe.id}) }}">show</a>
                    <a href="{{ path('app_equipe_edit', {'id': equipe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_equipe_new') }}">Create new</a>
{% endblock %}

omnisport/templates/equipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Equipe{% endblock %}

{% block body %}
    <h1>Create new Equipe</h1>

    {{ include('equipe/_form.html.twig') }}

    <a href="{{ path('app_equipe_index') }}">back to list</a>
{% endblock %}

omnisport/templates/equipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equipe{% endblock %}

{% block body %}
    <h1>Equipe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equipe.id }}</td>
            </tr>
            <tr>
                <th>Nom_equipe</th>
                <td>{{ equipe.nomEquipe }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ equipe.photo }}</td>
            </tr>
            <tr>
                <th>Dirigeant</th>
                <td>{{ equipe.dirigeant }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_equipe_index') }}">back to list</a>

    <a href="{{ path('app_equipe_edit', {'id': equipe.id}) }}">edit</a>

    {{ include('equipe/_delete_form.html.twig') }}
{% endblock %}