omnisport/src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClubRepository::class)]
class Club
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_club = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $activite = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\OneToMany(mappedBy: 'club', targetEntity: Section::class)]
    private Collection $section;

    public function __construct()
    {
        $this->section = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClub(): ?string
    {
        return $this->nom_club;
    }

    public function setNomClub(string $nom_club): self
    {
        $this->nom_club = $nom_club;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getActivite(): ?string
    {
        return $this->activite;
    }

    public function setActivite(string $activite): self
    {
        $this->activite = $activite;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSection(): Collection
    {
        return $this->section;
    }

    public function addSection(Section $section): self
    {
        if (!$this->section->contains($section)) {
            $this->section->add($section);
            $section->setClub($this);
        }

        return $this;
    }

    public function removeSection(Section $section): self
    {
        if ($this->section->removeElement($section)) {
            // set the owning side to null (unless already changed)
            if ($section->getClub() === $this) {
                $section->setClub(null);
            }
        }

        return $this;
    }
}

omnisport/src/Form/ClubType.php
<?php

namespace App\Form;

use App\Entity\Club;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ClubType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_club')
            ->add('description')
            ->add('activite')
            ->add('logo', FileType::class, [
                'label' => 'Photo du logo',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '5000k',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Image trop lourde',
                    ])
                ],
            ]);;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Club::class,
        ]);
    }
}

omnisport/src/Controller/ClubController.php
<?php

namespace App\Controller;

use App\Entity\Club;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/club')]
class ClubController extends AbstractController
{
    #[Route('/', name: 'app_club_index', methods: ['GET'])]
    public function index(ClubRepository $clubRepository): Response
    {
        return $this->render('club/index.html.twig', [
            'clubs' => $clubRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/new', name: 'app_club_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ClubRepository $clubRepository, SluggerInterface $slugger): Response
    {
        $club = new Club();
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('logo')->getData();
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $newFilename
                );

                $club->setLogo($newFilename);
                $clubRepository->save($club, true);

                return $this->redirectToRoute('app_club_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->renderForm('club/new.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_show', methods: ['GET'])]
    public function show(Club $club): Response
    {
        return $this->render('club/show.html.twig', [
            'club' => $club,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_club_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Club $club, ClubRepository $clubRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('logo')->getData();
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $newFilename
                );

                $club->setLogo($newFilename);
                $clubRepository->save($club, true);
            

            return $this->redirectToRoute('app_club_index', [], Response::HTTP_SEE_OTHER);
        }}

        return $this->renderForm('club/edit.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_delete', methods: ['POST'])]
    public function delete(Request $request, Club $club, ClubRepository $clubRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $club->getId(), $request->request->get('_token'))) {
            $clubRepository->remove($club, true);
        }

        return $this->redirectToRoute('app_club_index', [], Response::HTTP_SEE_OTHER);
    }
}

omnisport/templates/club/_delete_form.html.twig
<form method="post" action="{{ path('app_club_delete', {'id': club.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
    <button class="btn">Delete</button>
</form>

omnisport/templates/club/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

omnisport/templates/club/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Club{% endblock %}

{% block body %}
    <h1>Edit Club</h1>

    {{ include('club/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_club_index') }}">back to list</a>

    {{ include('club/_delete_form.html.twig') }}
{% endblock %}

omnisport/templates/club/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club index{% endblock %}

{% block body %}
    <h1>Club index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_club</th>
                <th>Description</th>
                <th>Activite</th>
                <th>Logo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for club in clubs %}
            <tr>
                <td>{{ club.id }}</td>
                <td>{{ club.nomClub }}</td>
                <td>{{ club.description }}</td>
                <td>{{ club.activite }}</td>
                <td><img src="{{ asset('uploads/images/' ~ club.logo) }}" width="100"></td>
                <td>
                    <a href="{{ path('app_club_show', {'id': club.id}) }}">show</a>
                    <a href="{{ path('app_club_edit', {'id': club.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_club_new') }}">Create new</a>
{% endblock %}

omnisport/templates/club/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Club{% endblock %}

{% block body %}
    <h1>Create new Club</h1>

    {{ include('club/_form.html.twig') }}

    <a href="{{ path('app_club_index') }}">back to list</a>
{% endblock %}

omnisport/templates/club/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club{% endblock %}

{% block body %}
    <h1>Club</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ club.id }}</td>
            </tr>
            <tr>
                <th>Nom_club</th>
                <td>{{ club.nomClub }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ club.description }}</td>
            </tr>
            <tr>
                <th>Activite</th>
                <td>{{ club.activite }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ club.logo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_club_index') }}">back to list</a>

    <a href="{{ path('app_club_edit', {'id': club.id}) }}">edit</a>

    {{ include('club/_delete_form.html.twig') }}
{% endblock %}