omnisport/src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_section = null;

    #[ORM\ManyToOne(inversedBy: 'section')]
    private ?Club $club = null;

    #[ORM\OneToMany(mappedBy: 'section', targetEntity: Equipe::class)]
    private Collection $equipe;

    public function __construct()
    {
        $this->equipe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSection(): ?string
    {
        return $this->nom_section;
    }

    public function setNomSection(string $nom_section): self
    {
        $this->nom_section = $nom_section;

        return $this;
    }

    public function getClub(): ?Club
    {
        return $this->club;
    }

    public function setClub(?Club $club): self
    {
        $this->club = $club;

        return $this;
    }

    /**
     * @return Collection<int, Equipe>
     */
    public function getEquipe(): Collection
    {
        return $this->equipe;
    }

    public function addEquipe(Equipe $equipe): self
    {
        if (!$this->equipe->contains($equipe)) {
            $this->equipe->add($equipe);
            $equipe->setSection($this);
        }

        return $this;
    }

    public function removeEquipe(Equipe $equipe): self
    {
        if ($this->equipe->removeElement($equipe)) {
            // set the owning side to null (unless already changed)
            if ($equipe->getSection() === $this) {
                $equipe->setSection(null);
            }
        }

        return $this;
    }
}

omnisport/src/Form/SectionType.php
<?php

namespace App\Form;

use App\Entity\Club;
use App\Entity\Section;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SectionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_section')
            ->add('club', EntityType::class, [ 'class' => Club::class, 'choice_label' => 'nom_club', ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Section::class,
        ]);
    }
}

omnisport/src/Controller/SectionController.php
<?php

namespace App\Controller;

use App\Entity\Section;
use App\Form\SectionType;
use App\Repository\SectionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/section')]
class SectionController extends AbstractController
{
    #[Route('/', name: 'app_section_index', methods: ['GET'])]
    public function index(SectionRepository $sectionRepository): Response
    {
        return $this->render('section/index.html.twig', [
            'sections' => $sectionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_section_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SectionRepository $sectionRepository): Response
    {
        $section = new Section();
        $form = $this->createForm(SectionType::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sectionRepository->save($section, true);

            return $this->redirectToRoute('app_section_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('section/new.html.twig', [
            'section' => $section,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_section_show', methods: ['GET'])]
    public function show(Section $section): Response
    {
        return $this->render('section/show.html.twig', [
            'section' => $section,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_section_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Section $section, SectionRepository $sectionRepository): Response
    {
        $form = $this->createForm(SectionType::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sectionRepository->save($section, true);

            return $this->redirectToRoute('app_section_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('section/edit.html.twig', [
            'section' => $section,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_section_delete', methods: ['POST'])]
    public function delete(Request $request, Section $section, SectionRepository $sectionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$section->getId(), $request->request->get('_token'))) {
            $sectionRepository->remove($section, true);
        }

        return $this->redirectToRoute('app_section_index', [], Response::HTTP_SEE_OTHER);
    }
}

omnisport/templates/section/_delete_form.html.twig
<form method="post" action="{{ path('app_section_delete', {'id': section.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ section.id) }}">
    <button class="btn">Delete</button>
</form>

omnisport/templates/section/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

omnisport/templates/section/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Section{% endblock %}

{% block body %}
    <h1>Edit Section</h1>

    {{ include('section/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_section_index') }}">back to list</a>

    {{ include('section/_delete_form.html.twig') }}
{% endblock %}

omnisport/templates/section/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Section index{% endblock %}

{% block body %}
    <h1>Section index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_section</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for section in sections %}
            <tr>
                <td>{{ section.id }}</td>
                <td>{{ section.nomSection }}</td>
                <td>
                    <a href="{{ path('app_section_show', {'id': section.id}) }}">show</a>
                    <a href="{{ path('app_section_edit', {'id': section.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_section_new') }}">Create new</a>
{% endblock %}

omnisport/templates/section/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Section{% endblock %}

{% block body %}
    <h1>Create new Section</h1>

    {{ include('section/_form.html.twig') }}

    <a href="{{ path('app_section_index') }}">back to list</a>
{% endblock %}

omnisport/templates/section/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Section{% endblock %}

{% block body %}
    <h1>Section</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ section.id }}</td>
            </tr>
            <tr>
                <th>Nom_section</th>
                <td>{{ section.nomSection }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_section_index') }}">back to list</a>

    <a href="{{ path('app_section_edit', {'id': section.id}) }}">edit</a>

    {{ include('section/_delete_form.html.twig') }}
{% endblock %}